name: build-docker-image-push-to-gcr

on:
  workflow_call:
    inputs:
      GITHUB_REF:
        required: true
        type: string
      GITHUB_SHA:
        required: true
        type: string
      IMAGE:
        required: true
        type: string
    secrets:
      REGISTRY_HOSTNAME:
        required: true
        type: string
      SERVICE_ACCOUNT:
        required: true
        type: string
      WORKLOAD_IDENTITY_PROVIDER:
        required: true
        type: string

jobs:
  build-tag-deploy:

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    
    steps:
    # actions/checkout MUST come before auth
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        token_format: 'access_token'
        workload_identity_provider: "${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}"
        service_account: "${{ secrets.SERVICE_ACCOUNT }}" 
        
    - name: Build
      run: |
        export TAG=`echo ${{ inputs.GITHUB_REF }} | awk -F/ '{print $NF}'`
        echo $TAG
        docker build -t "${{ secrets.REGISTRY_HOSTNAME }}"/"${{ inputs.IMAGE }}":"$TAG" \
          --build-arg GITHUB_SHA="${{ inputs.GITHUB_SHA }}" \
          --build-arg GITHUB_REF="${{ inputs.GITHUB_REF }}" .    
    
    - name: Publish
      run: |
        export TAG=`echo ${{ inputs.GITHUB_REF }} | awk -F/ '{print $NF}'`
        echo $TAG
        echo '${{ steps.auth.outputs.access_token }}' | docker login -u oauth2accesstoken --password-stdin https://gcr.io 
        docker push "${{ secrets.REGISTRY_HOSTNAME }}"/"${{ inputs.IMAGE }}":"$TAG"
        docker tag "${{ secrets.REGISTRY_HOSTNAME }}"/"${{ inputs.IMAGE }}":"$TAG" "${{ secrets.REGISTRY_HOSTNAME }}"/"${{ inputs.IMAGE }}":latest
        docker push "${{ secrets.REGISTRY_HOSTNAME }}"/"${{ inputs.IMAGE }}":latest
